version: '3.8'

services:

  backend:
    build: .
    ports:
     - "3000:3000"
    volumes:
     - app-data:/app/logs
    networks:
     - app-net

volumes:
  app-data:
networks:
  app-net:
    driver: bridge

